### ISSUE TITLE
VSCODE et GITBASH?

### ISSUE THREAD

**Issue by Joseceppic2020** [formeka/docker#4]
Bonjour Mehdi.
J'ai le droit d'utiliser vscode et gitbash? wsl2 n'st pas activé avec mon windows11

**Comment by formeka** [comment]
Bonjour José,
Comment est ce possible de se rendre compte qu'on a un souci avec wsl2 à 15h00 ! 
J'ai le droit d'utiliser vscode et gitbash?  : je ne sais pas trop comment te repondre !!!!!?
