### ISSUE TITLE
doker 

### ISSUE THREAD

**Issue by noraceppic** [formeka/docker#5]
bonjour mehdi 
j'ai suivi les étape du la doc node js 
donc J'ai crée  dockerfile et là je suis bloque je narrive pas a excuter cette commande 

docker run -p 49160:3478 -d norala/node-web-app

jai ce message d'errure
PS C:\Users\messa\OneDrive\Bureau\foad-doker\docker> docker run -p 49160:3478 -d norala/node-web-app
Unable to find image 'norala/node-web-app:latest' locally
docker: Error response from daemon: manifest for norala/node-web-app:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

**Comment by formeka** [comment]
Bonjour Nora,
qu'elle la commande que tu as fait pour construire(build) ton image ?

**Comment by formeka** [comment]
`#9 1.134 npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/app/package.json'`

Il sembley avoir un probleme avec ton `package.json`

On voit tout ça lundi...

**Comment by noraceppic** [comment]
d'accord merci
